import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='hero_image'><Image src={'/jasmine-coro-3NgnoYlNKdk-unsplash.jpg'} alt='scholar' fill/></div>
      
      {children}
      </body>
    </html>
  )
}
